// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://mkhizqiisubwpxfhexco.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1raGl6cWlpc3Vid3B4ZmhleGNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzEwMTc3MzAsImV4cCI6MjA0NjU5MzczMH0.bXZxPlPaaBbNjpcfBoAwM3mI146HSZSGNcd7UEROqUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);